- name: Oh-my-zsh setup
  hosts: all
  collections:
    - den_is.tools
  roles:
  - role: ohmyzsh
    vars:
      # you can provide default set of settings at top level
      # each of these settings can be overwritten on per user basis
      omz_theme: fishy
      omz_extra_conf:
      - export EDITOR=nano
      - export VISUAL=$EDITOR
