---

- name: run initial ubuntu setup
  hosts: servers
  become: true
  become_user: root
  
  vars:
    username: brent
    zsh_theme: agnoster
  tasks:

  - name: update the apt package index
    become: yes
    apt: update_cache=yes

  - name: upgrade system packages
    become: yes
    apt: upgrade=yes

  - name: install important packages
    become: yes
    apt: 
        name: "{{ packages }}" 
    vars:
        packages:
        - curl
        - fonts-powerline
        - git
        - net-tools
        - zsh
        - qemu-guest-agent
        
  - name: remove cloud
    ignore_errors: yes # Sometimes prefers docker.io install?
    become: yes
    shell: |
        echo 'datasource_list: [ None ]' | sudo -s tee /etc/cloud/cloud.cfg.d/90_dpkg.cfg
        apt -y purge cloud-init
        rm -rf /etc/cloud/; sudo rm -rf /var/lib/cloud/

  - name: install docker
    ignore_errors: yes # Sometimes prefers docker.io install?
    become: yes
    shell: |
        apt -y install docker.io
        systemctl enable --now docker

  - name: add {{ username }} to docker group
    become: yes
    shell: |
        usermod -aG docker {{ username }}

  - name: set up zsh
    shell: |
        sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
        sed -i -e  's/ZSH_THEME=".*"/ZSH_THEME="{{ zsh_theme }}/"' ~/.zshrc
        chsh -s $(which zsh)
        git clone https://github.com/zsh-users/zsh-syntax-highlighting .oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        git clone https://github.com/zsh-users/zsh-autosuggestions .oh-my-zsh/custom/plugins/zsh-autosuggestions
        sed -i -e 's/plugins=\(((.*\n)*)\)/plugins=\($1\n  colored-man-pages\n  zsh-syntax-highlighting\n  zsh-autosuggestions\n/' ~/.zshrc

  - name: copy over aliases
    copy:
        src: aliases
        dest: ~/.zsh_aliases
        owner: "{{ username }}"

  - name: add loading of aliases to .zshrc
    shell: cat 'if [ -f ~/.zsh_aliases ]; then\n\t. ~/.zsh_aliases/nfi' >> ~/.zshrc

