- name: ZSH Theme Change
  hosts: all
  tasks:
    - name: Change .zshrc theme
      ansible.builtin.replace:
        path: "{{ ansible_env.HOME }}/.zshrc"
        regexp: 'ZSH_THEME="essembeh"'
        replace: 'ZSH_THEME="agnoster"'
